# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create(first_name: "Lewis", last_name: "Hamilton", email: "demo@gmail.com", password: "asdf123")
User.create(first_name: "Sebastian", last_name: "Vettel", email: "svettel@gmail.com", password: "asdf123")
Car.create(owner_id: 1, address: "610 East 11th Street", city: "New York", state: "NY", longitude: -73.9809976, latitude: 40.7270074, year: 2014, make: "MERCEDES-BENZ", model:"SLS-CLASS AMG", price: 630, description: "The SLS Black Series' gem of an engine is derived from the SLS AMG GT’s naturally aspirated and aurally gifted 6.2-liter V-8. An additional 39 horsepower and a shift in the power peak by 600 revs translate to a meaty 622 horsepower at 7400 rpm.", hp: 622, mpg: 15, fuel_type: "Gasoline", doors: 2, seats: 2, vin: "WDDRJ7HA4EA011147")
Car.create(owner_id: 2, address: "1301 Alaskan Way", city: "Seattle", state: "WA", longitude: -122.3423189, latitude: 47.6059459, year: 1990, make: "FERRARI", model:"F40", price: 24113, description: "No Ferrari road car is more closely associated with Enzo Ferrari than the F40, the final project under the direction of Il Commendatore before his death in 1988. Built to commemorate the Italian carmaker's 40th anniversary, the F40 was, at its introduction in 1987, Ferrari's most powerful production car to date. Its 2936cc twin-turbocharged V8, nestled beneath the sloping buttresses of the berlinetta coupe's roofline, produced 478bhp and 426 lb-ft (577 Nm) of torque, delivering 'supercar' levels of performance: 0-60 mph in 3.8 seconds and, more significantly, a top speed of 201mph (324km/h). No production car before the F40 had ever pushed beyond that barrier.", hp: 478, mpg: 13, fuel_type: "Gasoline", doors: 2, seats: 2, vin: "ZFFMN34A6L0087030")
Feature.create(name: "All-wheel drive")
Feature.create(name: "Android Auto")
Feature.create(name: "Apple CarPlay")
Feature.create(name: "AUX input")
Feature.create(name: "Backup camera")
Feature.create(name: "Bike rack")
Feature.create(name: "Blind spot warning")
Feature.create(name: "Bluetooth")
Feature.create(name: "Child seat")
Feature.create(name: "Convertible")
Feature.create(name: "GPS")
Feature.create(name: "Heated Seats")
Feature.create(name: "Keyless entry")
Feature.create(name: "Pet friendly")
Feature.create(name: "Ski rack")
Feature.create(name: "Snow tires or chains")
Feature.create(name: "Sunroof")
Feature.create(name: "Toll pass")
Feature.create(name: "USB charger")
Feature.create(name: "USB input")
Feature.create(name: "Wheelchair accessible")
CarFeature.create(car_id: 1, feature_id: 5)
CarFeature.create(car_id: 1, feature_id: 7)
CarFeature.create(car_id: 1, feature_id: 8)
CarFeature.create(car_id: 1, feature_id: 11)
CarFeature.create(car_id: 1, feature_id: 12)
CarFeature.create(car_id: 1, feature_id: 17)
